    target(A,B) :- zero(B,B),zero(B,A).                              
    target(A,B) :- inv_54(C,A),inv_54(C,A).                          
     inv_0(A,B) :- inv_84(A,B),inv_37(A,B).                          
     inv_0(A,B) :- zero(C,A),zero(B,B).                              
     inv_1(A,B) :- zero(B,A),zero(C,B).                              
     inv_1(A,B) :- inv_33(B,C),inv_37(A,C).                          
     inv_2(A,B) :- inv_3(A,B),inv_41(A,B).                           
     inv_2(A,B) :- suk(B,C),zero(B,B).                               
     inv_3(A,B) :- inv_54(C,A),inv_82(B,C).                          
     inv_3(A,B) :- zero(B,A),zero(C,B).                              
     inv_4(A,B) :- zero(A,C),zero(C,A).                              
     inv_4(A,B) :- zero(B,A),zero(C,C).                              
     inv_5(A,B) :- inv_51(B,B),inv_26(C,A).                          
     inv_5(A,B) :- zero(C,B),inv_39(A,B).                            
     inv_6(A,B) :- zero(C,A),zero(B,B).                              
     inv_6(A,B) :- inv_82(A,C),inv_69(B,C).                          
     inv_7(A,B) :- inv_37(B,A),inv_54(A,B).                          
     inv_7(A,B) :- zero(A,B),zero(C,C).                              
     inv_8(A,B) :- inv_79(C,C),inv_37(A,B).                          
     inv_8(A,B) :- zero(B,B),zero(B,A).                              
     inv_9(A,B) :- inv_37(A,B),inv_37(A,B).                          
     inv_9(A,B) :- zero(B,B),zero(B,B).                              
    inv_10(A,B) :- inv_37(B,A),inv_31(A,B).                          
    inv_10(A,B) :- zero(B,A),zero(B,A).                              
    inv_11(A,B) :- zero(C,B),zero(B,A).                              
    inv_11(A,B) :- inv_54(C,B),inv_54(C,A).                          
    inv_12(A,B) :- inv_51(B,A),inv_37(B,B).                          
    inv_12(A,B) :- zero(B,C),zero(B,C).                              
    inv_13(A,B) :- inv_76(C,B),inv_11(A,A).                          
    inv_13(A,B) :- zero(B,B),zero(C,A).                              
    inv_14(A,B) :- zero(B,A),zero(A,A).                              
    inv_14(A,B) :- inv_54(B,A),inv_54(C,A).                          
    inv_15(A,B) :- zero(A,B),zero(A,A).                              
    inv_15(A,B) :- inv_22(A,A),inv_37(A,B).                          
    inv_16(A,B) :- inv_37(B,A),inv_33(A,C).                          
    inv_16(A,B) :- zero(B,A),zero(B,A).                              
    inv_17(A,B) :- zero(B,A),zero(C,C).                              
    inv_17(A,B) :- inv_16(B,C),inv_51(A,A).                          
    inv_18(A,B) :- inv_63(B,C),inv_82(A,C).                          
    inv_18(A,B) :- zero(B,B),zero(A,B).                              
    inv_19(A,B) :- zero(B,B),zero(C,B).                              
    inv_19(A,B) :- inv_79(C,C),inv_22(B,B).                          
    inv_20(A,B) :- inv_54(A,B),inv_54(A,B).                          
    inv_20(A,B) :- zero(A,B),zero(B,B).                              
    inv_21(A,B) :- zero(C,A),zero(C,B).                              
    inv_21(A,B) :- inv_22(B,B),inv_19(B,B).                          
    inv_22(A,B) :- zero(B,A),zero(A,C).                              
    inv_22(A,B) :- inv_82(A,C),inv_54(C,A).                          
    inv_23(A,B) :- zero(B,A),zero(A,B).                              
    inv_23(A,B) :- inv_54(C,B),inv_37(A,C).                          
    inv_24(A,B) :- inv_54(C,B),inv_37(B,C).                          
    inv_24(A,B) :- zero(A,A),zero(B,B).                              
    inv_25(A,B) :- zero(A,A),zero(B,A).                              
    inv_25(A,B) :- inv_25(A,A),inv_82(B,C).                          
    inv_26(A,B) :- zero(B,A),zero(C,A).                              
    inv_26(A,B) :- inv_82(B,C),inv_54(C,A).                          
    inv_27(A,B) :- zero(A,B),zero(A,B).                              
    inv_27(A,B) :- inv_39(C,B),zero(C,C).                            
    inv_28(A,B) :- inv_54(C,B),inv_54(C,A).                          
    inv_28(A,B) :- zero(B,C),zero(A,B).                              
    inv_29(A,B) :- zero(B,A),zero(A,A).                              
    inv_29(A,B) :- inv_22(B,B),inv_11(B,B).                          
    inv_30(A,B) :- inv_37(B,A),inv_54(A,B).                          
    inv_30(A,B) :- zero(A,B),zero(C,B).                              
    inv_31(A,B) :- zero(B,B),zero(A,B).                              
    inv_31(A,B) :- inv_1(A,B),inv_84(B,A).                           
    inv_32(A,B) :- inv_33(A,C),inv_54(C,A).                          
    inv_32(A,B) :- zero(B,A),zero(A,C).                              
    inv_33(A,B) :- suk(C,A),suk(B,C).                                
    inv_33(A,B) :- zero(C,A),zero(A,A).                              
    inv_34(A,B) :- zero(B,B),zero(A,A).                              
    inv_34(A,B) :- inv_22(B,B),inv_37(A,B).                          
    inv_35(A,B) :- zero(B,A),zero(A,C).                              
    inv_35(A,B) :- inv_37(A,A),inv_37(B,C).                          
    inv_36(A,B) :- inv_39(C,B),inv_54(C,A).                          
    inv_36(A,B) :- zero(A,B),zero(C,B).                              
    inv_37(A,B) :- inv_37(B,C),inv_33(A,C).                          
    inv_37(A,B) :- zero(B,A),zero(B,A).                              
    inv_38(A,B) :- inv_52(C,B),inv_37(A,C).                          
    inv_38(A,B) :- zero(B,B),zero(A,C).                              
    inv_39(A,B) :- zero(B,C),zero(A,A).                              
    inv_39(A,B) :- inv_82(B,C),inv_37(A,C).                          
    inv_40(A,B) :- zero(C,C),zero(A,C).                              
    inv_40(A,B) :- inv_37(B,C),inv_54(B,A).                          
    inv_41(A,B) :- zero(C,B),zero(A,A).                              
    inv_41(A,B) :- inv_37(A,C),inv_33(B,C).                          
    inv_42(A,B) :- zero(B,C),inv_39(B,A).                            
    inv_42(A,B) :- inv_54(B,B),inv_57(A,A).                          
    inv_43(A,B) :- inv_54(C,B),inv_82(A,C).                          
    inv_43(A,B) :- inv_39(B,A),zero(C,A).                            
    inv_44(A,B) :- zero(A,B),inv_66(B,A).                            
    inv_44(A,B) :- inv_33(B,C),inv_37(B,A).                          
    inv_45(A,B) :- inv_30(A,B),inv_44(B,A).                          
    inv_45(A,B) :- inv_39(B,B),zero(A,A).                            
    inv_46(A,B) :- inv_39(B,A),zero(C,C).                            
    inv_46(A,B) :- inv_11(A,B),zero(C,A).                            
    inv_47(A,B) :- inv_37(A,B),inv_16(A,C).                          
    inv_47(A,B) :- zero(A,A),zero(A,C).                              
    inv_48(A,B) :- inv_37(A,C),inv_33(B,C).                          
    inv_48(A,B) :- zero(A,B),zero(C,B).                              
    inv_49(A,B) :- inv_25(A,A),inv_37(B,C).                          
    inv_49(A,B) :- zero(B,B),suk(A,C).                               
    inv_50(A,B) :- zero(B,C),zero(A,B).                              
    inv_50(A,B) :- inv_54(B,A),inv_54(A,B).                          
    inv_51(A,B) :- zero(A,C),zero(C,B).                              
    inv_51(A,B) :- inv_54(C,B),inv_82(A,C).                          
    inv_52(A,B) :- zero(A,B),zero(C,B).                              
    inv_52(A,B) :- inv_54(B,A),inv_54(B,A).                          
    inv_53(A,B) :- inv_39(B,B),inv_39(C,A).                          
    inv_53(A,B) :- zero(B,B),zero(A,B).                              
    inv_54(A,B) :- inv_37(A,C),inv_82(B,C).                          
    inv_54(A,B) :- zero(C,C),zero(A,B).                              
    inv_55(A,B) :- inv_24(B,B),suk(C,B).                             
    inv_55(A,B) :- inv_22(A,A),inv_39(B,C).                          
    inv_56(A,B) :- inv_12(C,B),zero(B,C).                            
    inv_56(A,B) :- inv_37(B,A),inv_3(C,B).                           
    inv_57(A,B) :- inv_82(B,C),inv_54(C,B).                          
    inv_57(A,B) :- zero(B,C),zero(A,B).                              
    inv_58(A,B) :- zero(A,B),zero(B,C).                              
    inv_58(A,B) :- inv_16(B,A),inv_54(A,B).                          
    inv_59(A,B) :- inv_54(B,A),inv_37(B,B).                          
    inv_59(A,B) :- inv_39(A,A),zero(C,B).                            
    inv_60(A,B) :- zero(C,B),zero(C,C).                              
    inv_60(A,B) :- inv_37(B,C),inv_51(A,A).                          
    inv_61(A,B) :- suk(B,C),suk(A,C).                                
    inv_61(A,B) :- inv_54(B,A),inv_54(B,A).                          
    inv_62(A,B) :- inv_37(A,B),inv_82(B,C).                          
    inv_62(A,B) :- zero(B,B),zero(B,B).                              
    inv_63(A,B) :- inv_22(A,C),zero(A,A).                            
    inv_63(A,B) :- inv_33(A,C),inv_54(C,A).                          
    inv_64(A,B) :- zero(C,A),zero(A,A).                              
    inv_64(A,B) :- inv_22(B,B),inv_22(A,B).                          
    inv_65(A,B) :- inv_37(A,A),inv_54(C,A).                          
    inv_65(A,B) :- zero(A,B),zero(A,A).                              
    inv_66(A,B) :- inv_37(B,C),inv_33(A,C).                          
    inv_66(A,B) :- zero(A,B),zero(A,A).                              
    inv_67(A,B) :- zero(A,A),zero(C,B).                              
    inv_67(A,B) :- inv_39(C,A),inv_37(B,C).                          
    inv_68(A,B) :- zero(A,B),inv_22(B,B).                            
    inv_68(A,B) :- inv_82(B,C),inv_37(A,B).                          
    inv_69(A,B) :- zero(C,A),zero(B,A).                              
    inv_69(A,B) :- inv_51(A,C),inv_33(A,C).                          
    inv_70(A,B) :- inv_37(A,C),inv_22(B,B).                          
    inv_70(A,B) :- zero(C,B),zero(B,B).                              
    inv_71(A,B) :- inv_54(C,B),inv_41(C,B).                          
    inv_71(A,B) :- zero(B,C),zero(C,B).                              
    inv_72(A,B) :- zero(C,A),zero(A,A).                              
    inv_72(A,B) :- zero(C,A),zero(B,C).                              
    inv_73(A,B) :- inv_22(A,A),inv_37(B,B).                          
    inv_73(A,B) :- inv_37(B,A),zero(B,A).                            
    inv_74(A,B) :- inv_39(A,A),zero(B,B).                            
    inv_74(A,B) :- inv_37(B,A),inv_37(A,B).                          
    inv_75(A,B) :- suk(B,C),zero(B,A).                               
    inv_75(A,B) :- inv_39(C,B),inv_54(C,B).                          
    inv_76(A,B) :- zero(A,B),zero(B,B).                              
    inv_76(A,B) :- inv_54(A,B),inv_19(A,B).                          
    inv_77(A,B) :- zero(A,B),inv_39(C,B).                            
    inv_77(A,B) :- inv_37(B,C),inv_22(B,B).                          
    inv_78(A,B) :- inv_22(A,B),zero(A,B).                            
    inv_78(A,B) :- inv_33(A,C),inv_11(C,C).                          
    inv_79(A,B) :- suk(A,C),suk(B,C).                                
    inv_79(A,B) :- inv_13(B,B),inv_12(A,B).                          
    inv_80(A,B) :- zero(B,A),zero(A,A).                              
    inv_80(A,B) :- inv_37(A,A),inv_37(B,A).                          
    inv_81(A,B) :- inv_54(B,A),inv_54(B,A).                          
    inv_81(A,B) :- zero(B,B),zero(A,B).                              
    inv_82(A,B) :- zero(C,A),zero(A,C).                              
    inv_82(A,B) :- suk(C,A),suk(B,C).                                
    inv_83(A,B) :- zero(C,B),zero(C,A).                              
    inv_83(A,B) :- inv_54(A,A),inv_31(B,B).                          
    inv_84(A,B) :- zero(C,C),zero(A,B).                              
    inv_84(A,B) :- inv_1(C,B),inv_82(A,C).                           
    inv_85(A,B) :- zero(C,A),zero(B,A).                              
    inv_85(A,B) :- inv_33(B,C),inv_22(A,A).                          
    inv_86(A,B) :- zero(C,A),zero(C,B).                              
    inv_86(A,B) :- inv_37(A,C),inv_37(B,C).                          
    inv_87(A,B) :- zero(A,A),zero(B,B).                              
    inv_87(A,B) :- inv_11(B,B),inv_54(B,A).                          
    inv_88(A,B) :- inv_25(A,B),inv_97(A,B).                          
    inv_88(A,B) :- inv_51(B,A),suk(B,C).                             
    inv_89(A,B) :- zero(A,B),inv_57(B,B).                            
    inv_89(A,B) :- inv_37(B,C),inv_33(B,C).                          
    inv_90(A,B) :- inv_19(B,B),inv_22(A,B).                          
    inv_90(A,B) :- zero(C,C),zero(C,A).                              
    inv_91(A,B) :- zero(A,C),zero(B,C).                              
    inv_91(A,B) :- inv_33(A,C),inv_39(B,B).                          
    inv_92(A,B) :- inv_33(A,C),inv_30(B,C).                          
    inv_92(A,B) :- zero(B,A),zero(A,C).                              
    inv_93(A,B) :- inv_84(B,B),inv_37(B,A).                          
    inv_93(A,B) :- zero(B,C),zero(A,A).                              
    inv_94(A,B) :- zero(B,B),zero(B,A).                              
    inv_94(A,B) :- inv_33(B,C),inv_39(B,B).                          
    inv_95(A,B) :- zero(B,C),zero(C,A).                              
    inv_95(A,B) :- inv_39(A,A),inv_54(C,B).                          
    inv_96(A,B) :- inv_37(A,C),inv_82(B,C).                          
    inv_96(A,B) :- zero(B,A),zero(B,B).                              
    inv_97(A,B) :- inv_1(A,B),inv_37(A,B).                           
    inv_97(A,B) :- zero(A,B),zero(B,A).                              
    inv_98(A,B) :- inv_39(B,B),suk(C,B).                             
    inv_98(A,B) :- zero(A,C),zero(B,C).                              
    inv_99(A,B) :- zero(C,C),zero(C,A).                              
    inv_99(A,B) :- inv_37(A,A),suk(C,A).  